config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  resources :users
  resources :money_requests, except: [:show] 
  get '/all_requests', to: 'money_requests#show', as: 'all_request' 

  #Routing Nested Resources
  resources :money_requests do
    resources :loans, only: [:new, :create, :index, :show]
  end
  resources :loans, only: [:show, :index, :update]

  resources :loans do
    resources :payments, only: [:new, :create, :index, :show]
  end
  resources :payments, only: [:show, :index]


  root to: 'application#welcome'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :money_requests
    has_many :loans, through: :money_requests
    has_many :payments


    def self.find_or_create_by_omniauth(auth_hash)
        self.where(email: auth_hash['info']['email']).first_or_create do |user|
            user.password = SecureRandom.hex
            user.uid = auth_hash['uid']
            user.name = auth_hash['info']['name']
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            @error = "Some information is missing or User already exist"
            redirect_to new_user_path
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    def delete
        @user = User.find(params[:id])
        user.destroy
        redirect_to signin_path 
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :card_token, :card_type)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="new-user container">
    <div class="form-group col-md-6"> 
        <h2>Update your account</h2>
        <p><%= @error %></p>
        <%= form_for @user do |f| %>
            <p>Name: <%= f.text_field :name, :class => "form-control" %></p>
            <p>Password: <%= f.text_field :password, :class => "form-control" %></p>
            <p>Email: <%= f.text_field :email, :class => "form-control" %></p>
            <p>Card type <%= f.select :card_type, options_for_select(["Select One", "amex", "visa", "master card" ]) %></p>
            <p>Credit / Debit Card # <%= f.text_field :card_token, maxlength: 16 %></p>
            <br><%= f.submit "Update", :class => "btn btn-success" %>  
        <% end %><br>
        <%= link_to 'Go back to my home page ', user_path(current_user.id), :class => "btn btn-dark" %>
    </div>
</section>

app/views/users/new.html.erb
<section class="new-user container">
    <div class="form-group col-md-6"> 
        <h2>Create your account</h2>
        <p><%= @error %></p>
        <%= form_for @user do |f| %>
            <p>Name: <%= f.text_field :name, :class => "form-control" %></p>
            <p>Password: <%= f.text_field :password, :class => "form-control" %></p>
            <p>Email: <%= f.text_field :email, :class => "form-control" %></p>
            <br><%= f.submit "Signup", :class => "btn btn-dark" %>  
        <% end %>
        <br><p>Login with your social media account</p>
        <%= link_to(raw("<i class=\"fab fa-facebook-f\"></i> Facebook"), "/auth/facebook", {:class => "btn btn-lg btn-primary active"}) %> 
    </div>
</section>

app/views/users/show.html.erb
<section class="curent-user container">
    <div class="form-group col-md-10"> 
        <br><h2>My account:</h2>
        <% if @user.card_token == nil %>
            <p class="text-danger"> <%= link_to 'Update', edit_user_path(@user.id), :class => "btn btn-danger" %> Payment information is missind. Please update your account, so you can receice your money </p>    
        <% else %>
            <%= link_to 'Update my account', edit_user_path(@user.id), :class => "btn btn-warning" %>   
        <% end %> <br>
        <p>Name: <%= @user.name %></p>
        <p>Email: <%= @user.email %></p>
        <%= link_to 'My loans', loans_path, :class => "btn btn-light" %><br>
        <%= link_to 'My money requests', money_requests_path, :class => "btn btn-light" %><br>
        <%= link_to 'All Requests', all_request_path, :class => "btn btn-light" %><br><br>

        <%= link_to 'Request money', new_money_request_path, :class => "btn btn-dark" %>
    </div>
</section>