config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  resources :users
  resources :money_requests, except: [:show] 
  get '/all_requests', to: 'money_requests#show', as: 'all_request' 

  #Routing Nested Resources
  resources :money_requests do
    resources :loans, only: [:new, :create, :index, :show]
  end
  resources :loans, only: [:show, :index, :update]

  resources :loans do
    resources :payments, only: [:new, :create, :index, :show]
  end
  resources :payments, only: [:show, :index]


  root to: 'application#welcome'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'


end

app/models/loan.rb
class Loan < ApplicationRecord
    
    has_many :payments
    belongs_to :money_request
    belongs_to :borrowed, class_name: "User", foreign_key: "borrowed_id"
    belongs_to :lender, class_name: "User", foreign_key: "lender_id"
    has_many :open_transaction, class_name: "Payment", foreign_key: "open_transaction_id"
    has_many :close_transaction, class_name: "Payment", foreign_key: "close_transaction_id"
    

    scope :complited, -> { where(status: 1) }
    scope :incompleted, -> { where(status: 0) }

    STATUS = {
        :incomplete => 0,
        :complete => 1
    }
    
    scope :completed, -> { where(status: STATUS[:complete]) }
    scope :incompleted, -> { where(status: STATUS[:incomplete]) }

    
    def incomplete?
        self.status == STATUS[:incomplete]
    end

    def complete?
        self.status == STATUS[:complete]
    end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
    include MoneyRequestsHelper, LoansHelper
    before_action :require_login

    def new
        @loan = Loan.new
    end

    def create
        @loan = current_user.loans.build(loan_params)
        if @loan.save
            current_money_request.update(status: 1)
            redirect_to new_loan_payment_path(@loan.id)
        else
            render :new
        end
    end

    def index
        @loans_borrowed = Loan.where(borrowed_id: current_user.id)
        @loans_lender = Loan.where(lender_id: current_user.id)
    end

    def update
        @loan = my_loan.update(loan_params)
        redirect_to loan_path(@loan)    
    end
  
    def show
        @loan = my_loan
    end
   
    private
    def loan_params
        params.require(:loan).permit(:money_request_id, :lender_id, :borrowed_id, :amount_cents, :closing_loan_day, :opening_loan_day, :percentage, :open_transaction_id, :close_transaction_id, :total_paid)
    end
end

app/helpers/loans_helper.rb
module LoansHelper

    PERCENTAGE = {
        :short_term => 2,
        :long_term => 5
    }

    def set_terms
        if (current_money_request.terms - Date.today) >= 60
            PERCENTAGE[:short_term]
        else
            PERCENTAGE[:long_term]
        end
    end

    def current_loan
        Loan.find(params[:loan_id])
    end

    def my_loan
        Loan.find(params[:id])
    end

    def loan_terms
        TimeDifference.between(my_loan.money_request.terms, my_loan.opening_loan_day).humanize
    end

    def days_left
        TimeDifference.between(my_loan.money_request.terms, Date.today).humanize
    end

    def total_paid
        a = current_loan.percentage.to_f / 100 + 1
        current_loan.amount_cents.to_f * a
    end
end

app/views/loans/close.html.erb
<section class="close-loan container">
    <div class="form-group col-md-10"><br>
        <h4 class="text-dark"> By clicking "Close my loan" you are accepting the following  conditions:</h4>
          <p class="text-dark"> I`m, <%= current_user.name %>, going to lend <%= current_money_request.amount %> USD to <%= current_money_request.borrowed.name %> for <%= request_terms %> </p>
        <p class="text-dark"> Borrowed (<%= current_money_request.borrowed.name %>) undertakes to refund <%= current_money_request.amount %> USD + <%= set_terms %> % * before <%= current_money_request.terms %> .</p>
        
        <%= form_for @loan, url: money_request_loans_path, method: :post do |f| %>  

            <%= f.hidden_field :total_paid, :value => total_paid %>
            <%= f.hidden_field :closing_loan_day, :value => Date.today %>
            <%= f.submit "Close my loan", :class => "btn btn-success" %>
        <% end %>
        <br></br>
        <%= link_to 'Go back to the Home page', user_path(current_user.id), :class => "btn btn-dark" %>     
    </div>
</section>  

app/views/loans/index.html.erb
<section class="borrowed-loans container-fluid">
<table class="table table-bordered table-striped table-sm">
    <% if @loans_borrowed.length < 1  %>
        <br><h3> Hi <%= current_user.name %>! You didn`t borrow money from anyone. </h3>      
    <% else %>
        <br><h3> Hi <%= current_user.name %>! Here are all loans where you borrowed money: </h3>
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Lender name</th>
            <th scope="col">Borrowed name</th>
            <th scope="col">Amount</th>
            <th scope="col">Opening Day</th>
            <th scope="col">Percentage</th>
            <th scope="col">Closing Day</th>
            <th scope="col">Status</th>
            <th scope="col">Total Paid</th>
        </tr>
        </thead>
        <tbody>
        <% @loans_borrowed.each_with_index do |loan, index|  %>
        <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= loan.lender.name %></td>
            <td><%= loan.borrowed.name %></td>
            <td><%= loan.amount_cents %> USD </td>
            <td><%= loan.opening_loan_day.to_date %></td>
            <td><%= loan.percentage %>%</td> 
            <td><% if loan.closing_loan_day == nil %>
                Estimated closing day <%= loan.money_request.terms %>
              <% else %>
                  <%= loan.closing_loan_day %> 
            <% end %></td>
            <td><% if loan.status == 0 %>                
            <p class="text-primary"> Not paid yet <%= link_to "Close your Loan", new_loan_payment_path(loan.id), :class => "btn btn-primary" %> </p>
            <% else %>
                Paid
            <% end %></td>
            <td><% if loan.total_paid == nil %>
              Not paid yet
          <% else %>
            <%= loan.total_paid %> USD 
          <% end %></td>
          <% if loan.status == 0 && loan.borrowed_id == current_user.id %>
            <td class="table-danger">
             <p class="text-primary"> You have <%= TimeDifference.between(loan.money_request.terms, Date.today).in_days.to_i %> days left to pay your loan</p>
          <% end %><br></td>
      <% end %>
        </tr>
    </tbody>
    <% end %>
</table>
</section>  
<section class="lender-loans container-fluid">
<table class="table table-bordered table-striped table-sm">
    <% if @loans_lender.length < 1  %>
        <br><h3> You didn`t lend money to anyone. </h3>
    <% else %>
        <br><h3> Here are all loans where you lend money: </h3>
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Lender name</th>
                <th scope="col">Borrowed name</th>
                <th scope="col">Amount</th>
                <th scope="col">Opening Day</th>
                <th scope="col">Percentage</th>
                <th scope="col">Closing Day</th>
                <th scope="col">Status</th>
                <th scope="col">Total Paid</th>
            </tr>
        </thead>
        <tbody>
            <% @loans_lender.each_with_index do |loan, index|  %>
            <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= loan.lender.name %></td>
                <td><%= loan.borrowed.name %></td>
                <td><%= loan.amount_cents %> USD </td>
                <td><%= loan.opening_loan_day.to_date %></td>
                <td><%= loan.percentage %>%</td> 
                <td><% if loan.closing_loan_day == nil %>
                    Estimated closing day <%= loan.money_request.terms %>
                <% else %>
                    <%= loan.closing_loan_day %> 
                <% end %></td>
                <td><% if loan.status == 0 %>
                    Not paid yet
                <% else %>
                    Paid
                <% end %></td>
                <td><% if loan.total_paid == nil %>
                Not paid yet
            <% else %>
                <%= loan.total_paid %> USD
            <% end %></td>
        <% end %>
            </tr>
        </tbody>
    <% end %>
</table>
<%= link_to 'Go back to Home page ', user_path(current_user.id), :class => "btn btn-dark" %>
</section>  

app/views/loans/new.html.erb
<section class="new-loan container">
    <div class="form-group col-md-10"><br>
        <h4 class="text-dark"> By clicking "Lend money" you are accepting the following conditions:</h4>
          <p class="text-dark"> I`m, <%= current_user.name %>, going to lend <%= current_money_request.amount %> USD to <%= current_money_request.borrowed.name %> for <%= request_terms %> </p>
        <p class="text-dark"> Borrowed (<%= current_money_request.borrowed.name %>) undertakes to refund <%= current_money_request.amount %> USD + <%= set_terms %> % * before <%= current_money_request.terms %> .</p>
        <%= form_for @loan, url: money_request_loans_path, method: :post do |f| %>  
            <%= f.hidden_field :money_request_id, :value => current_money_request.id %>
            <%= f.hidden_field :lender_id, :value => current_user.id %>
            <%= f.hidden_field :borrowed_id, :value => current_money_request.borrowed_id %>
            <%= f.hidden_field :amount_cents, :value => current_money_request.amount %>
            <%= f.hidden_field :opening_loan_day, :value => Date.today %>
            <%= f.hidden_field :percentage, :value => set_terms %> 
            <%= f.submit "Lend money", :class => "btn btn-success" %>
        <% end %>
        <br></br>
        <%= link_to 'Go back to the Home page', user_path(current_user.id), :class => "btn btn-dark" %>     
    </div>
</section>  

app/views/loans/show.html.erb
<section class="show-loan container">
<table class="table table-bordered table-sm table table-striped">
<h2 class="text-danger"> Loan details:</h2>
<thead class="table table-sm">
    <tr>
        <th scope="col">Lender name</th>
        <td><%= @loan.lender.name %></td>
    </tr>
</thead>
<tbody>
    <tr>
        <th scope="col">Borrowed name</th>
        <td><%= @loan.borrowed.name %></td>
    </tr>
    <tr class="table-success">
        <th scope="col">Amount</th>
        <td><%= @loan.amount_cents %> USD </td>
    </tr>
    <tr>            
        <th scope="col">Opening Day</th>
        <td><%= @loan.opening_loan_day.to_date %></td> 
    </tr>
    <tr>
        <th scope="col">Terms</th>
        <td><%= loan_terms %></td>          
    </tr>
    <tr>
        <th scope="col">Percentage</th>
        <td><%= @loan.percentage %>%</td>          
    </tr>
    <tr>
        <th scope="col">Closing Day</th>
        <td><% if @loan.closing_loan_day == nil %>
            Estimated closing day <%= @loan.money_request.terms %>
        <% else %>
            <%= @loan.closing_loan_day %> 
        <% end %></td>
    </tr>
    <tr> 
        <th scope="col">Status</th>
        <td><% if @loan.status = 0 %>
                Not paid yet
        <% else %>
                Paid
        <% end %></td>
    </tr>
    <tr class="table-primary"> 
        <th scope="col">Total Paid</th>
        <td><% if @loan.total_paid == nil %>
            Not paid yet
        <% else %>
            <%= @loan.total_paid %>
        <% end %></td>
    </tr>
</tbody>
</table>
    <% if @loan.status = 0 && @loan.borrowed_id == current_user.id %>
    <p class="text-danger"> You have left <%= days_left %> to pay your loan</p>
    <% end %><br>
<%= link_to 'Go back to my Home page ', user_path(current_user.id), :class => "btn btn-dark" %>
</section>  