config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  resources :users
  resources :money_requests, except: [:show] 
  get '/all_requests', to: 'money_requests#show', as: 'all_request' 

  #Routing Nested Resources
  resources :money_requests do
    resources :loans, only: [:new, :create, :index, :show]
  end
  resources :loans, only: [:show, :index, :update]

  resources :loans do
    resources :payments, only: [:new, :create, :index, :show]
  end
  resources :payments, only: [:show, :index]


  root to: 'application#welcome'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'


end

app/models/money_request.rb
class MoneyRequest< ApplicationRecord
    validates :amount, presence: true
    validates :terms, presence: true
    validates_date :terms, :after => lambda { Date.current },
                               :before_message => "please change your estimated payment day, must be future"

    has_one :loan
    has_one :user
    belongs_to :borrowed, class_name: 'User', foreign_key: 'borrowed_id'

    STATUS = {
        :incomplete => 0,
        :complete => 1
    }
    DATE = {
        :actual => Date.today + 7,
    }

    scope :completed, -> { where(status: STATUS[:complete]) }
    scope :incompleted, -> { where(status: STATUS[:incomplete]) }
    scope :actual_and_incompleted, -> { incompleted.where('terms > ?', DATE[:actual]) }

    def incomplete?
        self.status == STATUS[:incomplete]
    end

    def complete?
        self.status == STATUS[:complete]
    end

    def actual?
        self.terms > DATE[:actual]
    end

end

app/controllers/money_requests_controller.rb
class MoneyRequestsController < ApplicationController
    include MoneyRequestsHelper
    before_action :require_login

    def new
        @money_request = MoneyRequest.new
    end
    
    def create
        @money_request = MoneyRequest.new(money_request_params)
        if @money_request.save 
            redirect_to money_requests_path
        else
            @error = "Some information is missing"
            redirect_to new_money_request_path
        end
    end   
    
    def index
        @my_requests = MoneyRequest.where(borrowed_id: current_user.id)
    end
    
    def show
        @incomplete_money_requests = MoneyRequest.actual_and_incompleted
    end
    
    def edit
        @request = my_request
        if @request.incomplete?
            @request.save
        else
            @error = "Cannot be updated since the request was already completed"
        end
    end
    
    def update
        my_request.update(money_request_params)
        redirect_to money_requests_path
    end

    def destroy
        request = my_request
        if request.incomplete?
            request.destroy
            redirect_to money_requests_path
        else
            @error = "Cannot be deleted since the request was already completed"
        end
    end
    
    private
    
    def money_request_params
        params.require(:money_request).permit(:terms, :amount, :borrowed_id, :status)
    end
end

app/helpers/money_requests_helper.rb
module MoneyRequestsHelper
    
    def my_request
        MoneyRequest.find(params[:id])
    end

    def current_money_request
        MoneyRequest.find(params[:money_request_id])
    end

    def request_terms
        TimeDifference.between(current_money_request.terms, Date.today).humanize
    end

end

app/views/money_requests/edit.html.erb
<section class="edit-money-request container">
    <div class="form-group col-md-6"> 
        <br><h2>Edit money request:</h2>
        <p1><%= @error %></p1>
        <%= form_for @request do |f| %>
            <p>Change the day: <%= f.date_field :terms, min: Date.today,  :class => "form-control" %> </p>
            <p>Change amount (USD): <%= f.number_field :amount, min: 1, :class => "form-control" %></p>
            <%= f.submit "Edit", :class => "btn btn-dark" %>
            <%= link_to 'Delete', money_request_path(@request), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger" %>
        <% end %><br></br>
        <%= link_to 'Show my requests', money_requests_path, :class => "btn btn-dark"%>
        <%= link_to 'Home', user_path(current_user.id), :class => "btn btn-dark" %>
    </div>
</section>

app/views/money_requests/index.html.erb
<section class="money-request container">
<table class="table table-bordered table-striped table-sm">
    <% if @my_requests.length < 1  %>
        <br><h3> Hi <%= current_user.name %>! You do not have any of money requests yet. </h3>
    <% else %>
        <br><h3> Hi <%= current_user.name %>! Here are all your money requests:</h3>   
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Amount, USD</th>
                <th scope="col">Estimated payment day</th>
                <th scope="col">Status</th>
                <th scope="col">Option</th>
            </tr>
        </thead>
        <tbody>
            <% @my_requests.each_with_index do |request, index|  %>
            <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= request.amount %></td>
                <td><%= request.terms %></td>

                <td><% if request.incomplete? && !request.actual? %>
                    <%= "Not actual. Pleasee change estimated payment day" %>
                <% elsif request.incomplete? && request.actual? %>
                    <%= "Pending" %>
                <% elsif request.loan.complete? %>
                    <%= "Paid" %>
                <% else %>
                    <%=  "Payment required" %>
                <% end %></td>

                <td><% if request.complete? %> 
                    <%= link_to "Check your Loan", money_request_loan_path(request.id, request.loan.id), :class => "btn btn-warning" %>
                <% else %>
                    <%= link_to "Edit Money Request", edit_money_request_path(request), :class => "btn btn-light" %>
                <% end %></td>
            </tr>
            <% end %><br>
        </tbody>
    <% end %>
</table>
    <%= link_to 'Request money', new_money_request_path, :class => "btn btn-dark" %>
    <%= link_to 'Home', user_path(current_user.id), :class => "btn btn-dark" %>
</section>





        

app/views/money_requests/new.html.erb
<section class="new-money-request container">
    <div class="form-group col-md-6"> 
        <br><h2>Create new money request:</h2>
        <p><%= @error %></p>
        <%= form_for @money_request do |f| %>
            <%= f.hidden_field :borrowed_id, :value => current_user.id %>      
            <p>I plan to repay the loan on: <%= f.date_field :terms, min: Date.today,  :class => "form-control" %> </p>
            <p>Amount (USD): <%= f.number_field :amount, min: 1, :class => "form-control" %></p>
            <%= f.submit "Create", :class => "btn btn-dark" %>
        <% end %><br></br>
        <%= link_to 'Show my requests', money_requests_path, :class => "btn btn-dark"%>
        <%= link_to 'Home', user_path(current_user.id), :class => "btn btn-dark" %>
    </div>
</section>

app/views/money_requests/show.html.erb
<section class="show-money-request container">
<table class="table table-bordered table-striped table-sm">
    <h2>Pending Money Requests:</h2>
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">User</th>
            <th scope="col">Amount, USD</th>
            <th scope="col">Estimated payment day</th>
            <th scope="col">Option</th>
        </tr>
    </thead>
    <tbody>
        <% @incomplete_money_requests.each_with_index do |request, index| %>
        <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= request.borrowed.name %></td>
            <td><%= request.amount %></td>
            <td><%= request.terms %></td>
            <td><% if current_user.id == request.borrowed_id %>
                <%= link_to "Edit Money Request", edit_money_request_path(request), :class => "btn btn-warning" %>
            <% else %>
                <%= link_to "Lend Money", new_money_request_loan_path(request.id), :class => "btn btn-info" %>
            <% end %></td>
        </tr>
        <% end %><br>
    </tbody>
</table>
<%= link_to 'Go back to my home page ', user_path(current_user.id), :class => "btn btn-dark" %>
</section>



    