config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  resources :users
  resources :money_requests, except: [:show] 
  get '/all_requests', to: 'money_requests#show', as: 'all_request' 

  #Routing Nested Resources
  resources :money_requests do
    resources :loans, only: [:new, :create, :index, :show]
  end
  resources :loans, only: [:show, :index, :update]

  resources :loans do
    resources :payments, only: [:new, :create, :index, :show]
  end
  resources :payments, only: [:show, :index]


  root to: 'application#welcome'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#signout'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>MyBank</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="/">My Bank</a>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">

          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="<%= signin_path %>">Sign In</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="<%= signout_path %>">Log Out</a>
        </li>

        </ul>
      </div>
    </nav>
    <div class="container" >
      <div class="row">
          <div class="col-sm-4 "> <%= image_tag ("/assets/finance.jpg"), :class => "img-thumbnail img-responsive" %></div>  
          <div class="col-sm-4 "> <%= image_tag ("/assets/hands.png"), :class => "img-thumbnail img-responsive" %></div>   
          <div class="col-sm-4"> <%= image_tag ("/assets/money.jpg"), :class => "img-thumbnail img-responsive" %></div>     
      </div>  
    </div>
    <%= yield %>
    <div class="container-fluid">
      <section><div id="map"></div></section>
      <footer class="footer text-xs-center"><div>(c) Copyright discoveryvip.com</div></footer>
    </div>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
 -->
    <%= stylesheet_link_tag 'application', 'fontawesome-all.css' %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDuZY3py3zXtArat18Ng72V8IbbJwi4UvE&callback=init" type="text/javascript"></script>
    <script>
      function init() {
          var lal = {
              lat: 40.77663,
              lng: -73.97177
          };
          var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 1,
              center: lal
          });
          var marker = new google.maps.Marker({
              position: lal,
              map: map
          })
      }
  </script>
  </body>
</html>